package ru.dbotthepony.mc.otm.client.render.entity

import net.minecraft.client.model.HierarchicalModel
import net.minecraft.client.renderer.entity.EntityRendererProvider
import net.minecraft.client.renderer.entity.MobRenderer
import net.minecraft.resources.ResourceLocation
import ru.dbotthepony.mc.otm.OverdriveThatMatters.loc
import ru.dbotthepony.mc.otm.client.model.entity.LoaderModel
import ru.dbotthepony.mc.otm.entity.Loader

class LoaderRenderer(context: EntityRendererProvider.Context)
	: MobRenderer<Loader, HierarchicalModel<Loader>>(context, LoaderModel.getModel(), 0.8f) {
	override fun getTextureLocation(entity: Loader): ResourceLocation = TEXTURE_LOCATION

	companion object {
		private val TEXTURE_LOCATION = loc("textures/entity/loader.png")
	}
}
